name: Manual

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

jobs:
  print-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch
        run: echo  ${{ inputs.branch }}
  test:
    uses: ./.github/workflows/test.yml
    with:
      branch: ${{ inputs.branch }}
